image: gradle:5.6.2-jdk12

variables:
  GRADLE_CACHE: plugins

cache:
  paths:
    - GRADLE_CACHE

stages:
  - test
  - build
  - artifact
  - deploy
  
test:
  stage: test  
  script:
    - gradle test  
  
build:
  stage: build
  script:
    - gradle build

deploy:
  stage: deploy
  script:
    - git remote add heroku https://victorfconti.$HEROKU_KEY@git.heroku.com/aula-devops-ci.git
    - git config user.email = GITLAB_USER_EMAIL 
    - git config user.name = GITLAB_USER_LOGIN
    - git push heroku --all
  environment:
    name: producao
    url: https://aula-devops-ci.herokuapp.com
  only:
    - master
  when: manual
