image: gradle:5.6.2-jdk12

stages:
  - test
  - build
  - artifact
  - deploy
  
test:
  stage: test  
  script:
    - gradle test  
  
build:
  stage: build
  script:
    - gradle build

deploy:
  stage: deploy
  script:
    - git remote add heroku https://victorfconti.$HEROKU_KEY@git.heroku.com/aula-devops-ci.git
    - git push heroku master
  environment:
    name: producao
    url: https://aula-devops-ci.herokuapp.com
  only:
    - master
  when: manual
