image: gradle:5.6.2-jdk12

variables:
  GRADLE_CACHE: plugins

cache:
  paths:
    - GRADLE_CACHE

stages:
  - test
  - build
  - artifact
  - deploy
  
test:
  stage: test  
  script:
    - gradle test  

    
coverage:
  stage: test
  script:
    - echo "Total 100%"
    
build:
  stage: build
  script:
    - gradle build

deploy:
  stage: deploy
  before_script:
    - git checkout master
  script:
    - git remote add heroku https://victorfconti:$HEROKU_KEY@git.heroku.com/aula-devops-ci.git
    - git config user.email = $GITLAB_USER_EMAIL 
    - git config user.name = $GITLAB_USER_LOGIN
    - git push -f heroku HEAD:master
  environment:
    name: producao
    url: https://aula-devops-ci.herokuapp.com
  only:
    - master
#  when: manual
